// Auto-generated by business-agent
const config = {
  name: "RoyalTrack",
  tagline: "Simplify your digital royalties",
  description: "Get accurate royalty estimates with RoyalTrack. Simplify your digital royalties with our easy-to-use calculator and tracking tools.",
  primaryColor: "emerald",
  accentColor: "green",
  features: ["Easy royalty calculation","Sales data management","Exportable results"],
  niche: "digital-downloads",
  targetAudience: "Digital creators, artists",
  monetization: ["Primary: Affiliate marketing for digital download platforms","Secondary: Sponsored content from creative software"],
  seoStrategy: "Target keywords: 'royalty calculator', 'digital creator', 'sales estimator'; Content strategy: Create informative blog posts and tutorials on managing digital sales and royalties.",
};

export default config;
