// Auto-generated by business-agent
const config = {
  name: "RoyalTrack",
  tagline: "Simplify your digital royalties",
  description: "RoyalTrack helps digital creators easily calculate and track royalties from various sales platforms. Efficiently manage your digital downloads revenue.",
  primaryColor: "emerald",
  accentColor: "green",
  features: ["Easy royalty calculation","Sales data management","Exportable results"],
  niche: "digital-downloads",
  targetAudience: "Digital creators, artists",
  monetization: ["Primary: Affiliate marketing for digital download platforms","Secondary: Sponsored content from creative software"],
  seoStrategy: "Target keywords: 'royalty calculator', 'digital creator', 'sales estimator'; Content strategy: Create informative blog posts and tutorials on managing digital sales and royalties.",
};

export default config;
